# Generated by Django 4.1.4 on 2023-01-02 11:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)])),
                ('text', models.TextField()),
                ('client_tags', models.ManyToManyField(blank=True, null=True, to='ClientManagement.clienttag')),
                ('network_code', models.ManyToManyField(blank=True, null=True, to='ClientManagement.clientnetworkcode')),
            ],
        ),
    ]
