# Generated by Django 4.1.4 on 2023-01-04 17:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagement', '0005_alter_client_tags_delete_message'),
        ('Mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client_tags',
            field=models.ManyToManyField(blank=True, to='ClientManagement.clienttag'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 17, 11, 31, 342875, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='network_code',
            field=models.ManyToManyField(blank=True, to='ClientManagement.clientnetworkcode'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('celery_task', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('RN', 'Running'), ('FL', 'Failed'), ('EX', 'Expired')], default='CR', max_length=2)),
                ('creation_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClientManagement.client')),
                ('mailing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Mailing.mailing')),
            ],
        ),
    ]
