# Generated by Django 4.1.4 on 2023-01-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mailing', '0002_alter_mailing_client_tags_alter_mailing_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mailing.mailing'),
        ),
    ]
