# Generated by Django 4.1.4 on 2023-01-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailing', '0003_alter_message_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='celery_task',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
