# Generated by Django 4.1.4 on 2023-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailing', '0004_message_id_alter_message_celery_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
