# Generated by Django 4.1.4 on 2023-01-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mailing', '0001_initial'),
        ('ClientManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mailing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mailing.mailing'),
        ),
        migrations.AddField(
            model_name='client',
            name='network_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ClientManagement.clientnetworkcode'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='ClientManagement.clienttag'),
        ),
    ]
