# Generated by Django 4.1.4 on 2023-01-02 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='network_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClientManagement.clientnetworkcode'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter the number in the format 7XXXXXXXXXX', regex='^7.*')]),
        ),
    ]
