# Generated by Django 4.1.4 on 2023-01-02 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagement', '0003_alter_client_network_code_alter_client_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter the number in the format 7XXXXXXXXXX', regex='^7.*')]),
        ),
        migrations.AlterField(
            model_name='clientnetworkcode',
            name='code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='clienttag',
            name='tag',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
