# Generated by Django 4.1.4 on 2023-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientManagement', '0004_rename_tag_client_tags_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ClientManagement.clienttag'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
